trigger:

  branches:
    exclude:
      - readme*
      - temp-*
      - exp-*

  paths:
    exclude:
      - README.md
      - docs/**
      - scripts/configurator/**
stages:
- stage: Test
  jobs:
    - job: interactive_gcc84
      container: 'vvaltchev/tilck-ci-build:v5'
      pool:
        vmImage: 'ubuntu-20.04'
      variables:
        CI: 1
        TCROOT: /tc/toolchain2-gcc84
        GTEST_SHUFFLE: 0
        TILCK_NO_LOGO: 1
        GCC_TC_VER: 8.4.0
        CMAKE_ARGS: >
          -DEXTRA_TCC=1
          -DEXTRA_VIM=1
          -DFB_CONSOLE_BANNER=0
          -DFB_CONSOLE_CURSOR_BLINK=0
          -DBOOT_INTERACTIVE=0
          -DPREFERRED_GFX_MODE_W=640
          -DPREFERRED_GFX_MODE_H=480
          -DKMALLOC_FREE_MEM_POISONING=1
      steps:
        - script: printenv
          displayName: Dump env
        - script: mkdir artifacts
          displayName: Create artifacts directory
        - script: ./scripts/build_generators/gcc_gcov
          displayName: Run CMake
        - script: make blahblah
          displayName: bad build cmd
        - script: make -j
          displayName: build kernel
        - script: |
            echo job: $SYSTEM_JOBIDENTIFIER
            mkdir artifacts
            echo hello >> artifacts/test-$SYSTEM_JOBIDENTIFIER.txt
        - task: PublishPipelineArtifact@1
          condition: always()
          inputs:
            targetPath: artifacts
            artifact: 'test-intr-gcc84'
            publishLocation: 'pipeline'

    - job: gcc_8_4_x86_64
      container: 'vvaltchev/tilck-ci-build:v5'
      pool:
        vmImage: 'ubuntu-20.04'
      variables:
        CI: 1
        TCROOT: /tc/toolchain2-gcc84-x86-64
        GTEST_SHUFFLE: 0
        TILCK_NO_LOGO: 1
        GCC_TC_VER: 8.4.0
        ARCH: x86_64
      steps:
        - script: printenv
          displayName: Dump env
        - script: ./scripts/cmake_run
          displayName: Run CMake
        - script: make -j
          displayName: Build the kernel
        - script: |
            echo job: $SYSTEM_JOBIDENTIFIER
            mkdir artifacts
            echo hello >> artifacts/test-$SYSTEM_JOBIDENTIFIER.txt
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: artifacts
            artifact: 'test-64-bit'
            publishLocation: 'pipeline'

